# This is a basic workflow to help you get started with Actions

name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: new-action-flow-test-org-1/action-repo-1@main
    - uses: new-action-flow-test-org-1/action-repo-2@main
